### ISSUE TITLE
Including react-querybuilder in a drag-n-drop application causes errors of "Cannot have two HTML5 backends at the same time."

### ISSUE THREAD

**Issue by kyrylostepanchuk** [react-querybuilder/react-querybuilder#276] opened 2022-01-24 20:18 UTC
Hello,

We are trying to use react-querybuilder in a React application that also uses Drag-N-Drop (via react-dnd).

Unfortunately, including react-querybuilder causes an infinite loop of errors of `Cannot have two HTML5 backends at the same time.`. We have attempted a workaround of overriding the `rootElement` of our application's `DndProvider`, but that seems to break drag-n-drop into react-querybuilder from the application.

A potential fix for this issue is the approach taken by react-sortable-tree, where the library exports the component as `SortableTreeWithoutDndContext`, relying on the application to create a DndProvider: https://github.com/frontend-collective/react-sortable-tree/blob/master/src/react-sortable-tree.js#L960

If necessary, I can try to create a diff with the changes that replicate the above fix.

Thank you!
Kyrylo Stepanchuk

**Comment by jakeboone02** [comment] 2022-01-24 22:46
Hi, @kyrylostepanchuk! I've been concerned about that situation ever since I implemented drag-and-drop (and I tried to replicate the issue with no luck -- see [this comment](https://github.com/react-querybuilder/react-querybuilder/issues/270#issuecomment-1017778885)).

Anyway, thank you so much for the link to the potential solution! I would definitely consider a PR that implemented something like that, or if you just wanted to send a diff I can commit it myself.

**Comment by kyrylostepanchuk** [comment] 2022-01-25 15:55
I'll try making a diff 👍

**Comment by jakeboone02** [comment] 2022-01-25 16:53
GitHub tells me this is your first-ever issue. Would you like some instructions on how to do a proper pull request, so you can get credited in the commit history?

**Comment by kyrylostepanchuk** [comment] 2022-01-25 18:23
I can forego the credit, but I'll let you know if my bitbucket workflow would easily translate. Diff first :)

**Comment by jakeboone02** [comment] 2022-01-25 18:27
Sounds good. Thanks again!

**Comment by jakeboone02** [comment] 2022-01-30 21:44
@kyrylostepanchuk - sorry to pester, but do you have an ETA on the diff? I'm close to releasing v4.2.0 and would like to include a fix for this bug.

**Comment by kyrylostepanchuk** [comment] 2022-01-31 14:34
@jakeboone02
Hi Jake,

This is as far as I was able to get. I was testing it in our application, and working through an issue ("item cannot be undefined"), when I got diverted. Maybe I'm missed something obvious 🤷 

Diff inside zip: 
[react-qb-dnd.zip](https://github.com/react-querybuilder/react-querybuilder/files/7971501/react-qb-dnd.zip)

**Comment by jakeboone02** [comment] 2022-01-31 22:10
@kyrylostepanchuk I implemented your suggested fix in #282 (also, I hope you don't mind, I marked the commit as co-authored by you -- I can undo that if you want).

Can you fork [this codesandbox](https://codesandbox.io/s/react-querybuilder-ci-idb7u) (it uses the new code), try to recreate the scenario and see if the problem is resolved?

**Comment by kyrylostepanchuk** [comment] 2022-02-01 15:27
https://codesandbox.io/s/react-querybuilder-ci-forked-jrjn6 seems to function correctly. I wrapped the outermost div in a DndProvider and the sandbox is able to run correctly.

**Comment by jakeboone02** [comment] 2022-02-01 16:12
Great! I'll merge the PR. Thanks again for all your help!

**Closed as completed** 2022-02-01 16:13 UTC

**Comment by kyrylostepanchuk** [comment] 2022-02-03 21:17
@jakeboone02 I just tested the latest 4.2.0 version with our application, and it seems to have worked. Many thanks! One last piece that was missing was involving our own webpack configuration. It may be due to the way dependencies are pulled in by npm (react-querybuilder would have its own copy). This was the fix:

react-dnd/react-dnd#3349

Our webpack config had to include this section to import all react-dnd code from the same place.
```
resolve: {
  alias: {
    'react-dnd': path.resolve('node_modules/react-dnd')
  }
},
```

Just FYI, in case it comes up for someone else.
