### ISSUE TITLE
Custom ValueEditor rerenders infinitely: 

### ISSUE THREAD

**Issue by Andonvr** [react-querybuilder/react-querybuilder#504] opened 2023-05-02 11:51 UTC
I'm trying to do something like [this](https://react-querybuilder.js.org/docs/tips/custom-with-fallback). My code looks like this:  
```
const pathToKey = (path: number[]) => {
  return path.reduce((acc, curr) => {
    return `${acc}[${curr}]`
  }, "")
}

export const CustomValueEditor: FC<ValueEditorProps> = (props: ValueEditorProps) => {
  console.log("Rendered")
  if (props.type === "text") {
    return (
      <div>
        <FilterTextField
          {...props}
          placeholder={`Enter ${props.fieldData.label} here`}
          key={pathToKey(props.path)}
        />
      </div>
    )
  }
  return <ValueEditor {...props} key={pathToKey(props.path)} />
}
```

But this way, "Rendered" keeps being logged. And the FilterTextField component keeps rerendering as well.  However, if I remove everything inside `if (props.type === "text") { ...}`, so that this really only returns `<ValueEditor ... />`, this does NOT happen! No unnecessary rerenders!

**Comment by jakeboone02** [comment] 2023-05-02 16:45
Closing as duplicate of #505.

**Closed as completed by jakeboone02** 2023-05-02 16:45 UTC
