### ISSUE TITLE
Multi-select editor type with custom operator not allowing multi selection

### ISSUE THREAD

**Issue by rorueda** [react-querybuilder/react-querybuilder#631] opened 2024-01-12 11:59 UTC
After upgrading from 6.5.1 to 6.5.4, I started having issues with multi-select fields. After some debugging I found the culprit is the fix for #551 (yes, that edge case you were afraid of :smile:).

What happens is that because of the change, if `listsAsArrays` is enabled then a field with the following configuration will not allow multi selection (and the 'Empty' option will never be selected):

```typescript
{
    name: 'test',
    label: 'Test',
    valueEditorType: 'multiselect',
    values: [
      { label: 'Empty', name: '' },
      { label: 'NotEmpty', name: 'not-empty' },
      { label: 'NotEmpty2', name: 'not-empty-2' },
    ],
    operators: [{ name: 'custom', label: 'custom' }],
}
```

I disabled the hook in a custom value editor as I don't need it, but I'm reporting because I think this default behavior is a little odd. 

My understanding is that the hook might be missing some handling for `listsAsArrays` and also that it should consider the `valueEditorType`  to make changes to the value.

**Comment by jakeboone02** [comment] 2024-01-12 15:03
Thanks for the report! Can you do a couple of things for me?

1. Create a sandbox or repo demonstrating the issue
2. Try the same code with `v7.0.0-alpha.5`

**Comment by rorueda** [comment] 2024-01-12 20:18
I've created the sandbox with `v7.0.0-alpha.5` (https://codesandbox.io/p/sandbox/react-querybuilder-issues-631-cqn77l)
and haven't noticed any change in behavior when comparing with `v6.5.4.

**Comment by jakeboone02** [comment] 2024-01-14 06:44
I agree this shouldn't be the expected behavior. Seems like the fix would be fairly simple? This is the current logic, as I laid out in https://github.com/react-querybuilder/react-querybuilder/issues/551#issuecomment-1691973492:

> - If the `useValueEditor` hook is executed (as when the default `ValueEditor` component is rendered),
> - and the `value` is an array (`Array.isArray(value) === true`),
> - and the `operator` is anything _other than_ `'between'`, `'notBetween'`, `'in'`, or `'notIn'`,
> - then update the `value` to `value[0]`.

The logic should be the same, with the addition of a check for `valueEditorType !== "multiselect"`, like this:

```diff
 - If the `useValueEditor` hook is executed (as when the default `ValueEditor` component is rendered),
 - and the `value` is an array (`Array.isArray(value) === true`),
 - and the `operator` is anything _other than_ `'between'`, `'notBetween'`, `'in'`, or `'notIn'`,
+- and the `valueEditorType` is anything _other_ than `'multiselect'`
 - then update the `value` to `value[0]`.
```

Does that sound right?

I forked your sandbox and added an updated version of `useValueEditor`:  https://codesandbox.io/p/devbox/react-querybuilder-issues-631-forked-zdp88w?file=%2Fsrc%2FuseValueEditorCustom.ts%3A36%2C1-36%2C32

**Comment by jakeboone02** [comment] 2024-01-14 07:00
Hopefully fixed in v7 by #632. If this works for v7 I'll patch v6 as well.

**Comment by rorueda** [comment] 2024-01-15 12:21
I did some testing using your sandbox and it looks great. Thanks for the quick response and fix.

**Comment by jakeboone02** [comment] 2024-01-15 16:03
That's good news. I'll try to get a v6 patch out soon.

**Closed as completed** 2024-01-15 17:59 UTC

**Comment by jakeboone02** [comment] 2024-01-15 18:51
[`v6.5.5`](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v6.5.5) was just released including the fix for this issue.

**Comment by A-EbrahimRSA** [comment] 2024-10-23 09:03
Just putting my findings here as an FYI for those that may encounter a similar problem as a result of these changes.

I had a Field which was using a multiselect, as well as the operators of '=' and 'in
```
{
    name: 'test',
    label: 'Test',
    valueEditorType: 'multiselect',
    values: [
      { label: 'Empty', name: '' },
      { label: 'NotEmpty', name: 'not-empty' },
      { label: 'NotEmpty2', name: 'not-empty-2' },
    ],
    operators: defaultOperators.filter(op => op.name === '=' || op.name === 'in' || op.name === 'notIn'),
}
```
When I would switch operators from 'in' => '=' whilst several values were selected I didn't get my intended behaviour of selecting the first item in the list. 

I had previously been using a custom ValueEditor control which also handled the issue #551 resolved but I aimed to remove that custom solution and rather use the built in fixes. Hence upgrading to v6.5.5 and getting the above issue.

The root cause of the 'bug' is that even though I am changing the operator to '=', since the valueEditorType='multiselect' it would still inherit all the values from the previous 'in' operator.

My fix for this was leveraging the function prop for the valueEditorType. My resulting Field looks as follows:

```
{
    name: 'test',
    label: 'Test',
    valueEditorType: (op)=>'!='.includes(op)?'select':'multiselect',
    values: [
      { label: 'Empty', name: '' },
      { label: 'NotEmpty', name: 'not-empty' },
      { label: 'NotEmpty2', name: 'not-empty-2' },
    ],
    operators: defaultOperators.filter(op => op.name === '=' || op.name === 'in' || op.name === 'notIn'),
}
```
I'm unsure if this functionality is still usable in v7 but thanks @jakeboone02 for this function prop its really nifty 🧐
