### ISSUE TITLE
[Bug] Combinator selector applies for entire group instead of particular position

### ISSUE THREAD

**Issue by alexandernst** [react-querybuilder/react-querybuilder#204] opened 2021-06-21 22:48 UTC
I have a use case where I want to create the following (simple) condition: `(foo AND bar OR xyz)`.

Using the [demo page](https://react-querybuilder.github.io/react-querybuilder/) I tried to add 3 rules and then change the second combinator to `OR`. Immediately after changing it to `OR`, the first combinator also changed to `OR`.

After doing some tests it seems that the combinator's behaviour is buggy. Changing one of the combinators causes all other combinators at the same group level to change (to the same value).

I recorded a video demoing the bug:

https://user-images.githubusercontent.com/89727/122836916-7c589c80-d2f3-11eb-9eef-55dd5bc07a6e.mov

**Comment by jakeboone02** [comment] 2021-06-22 14:45
This is the intended functionality.  All the combinators within a group must match because that's the only way to be sure, logically, what the complete query configuration actually means.  In your example `(foo AND bar OR xyz)`, it's not clear whether it means `((foo AND bar) OR xyz)`, or `(foo AND (bar OR xyz))`.  The way to represent it in the query builder would be one of the following configurations:

![image](https://user-images.githubusercontent.com/366438/122945797-ae86f000-d32d-11eb-96ae-30cc20fc2a14.png)

![image](https://user-images.githubusercontent.com/366438/122945841-b777c180-d32d-11eb-8904-af7952967323.png)

**Comment by alexandernst** [comment] 2021-06-22 15:46
Ah, I see. Since this is the expected behavior I would totally understand if you closed this issue. Nevertheless, I must disagree with your affirmation that there is no way of knowing the real meaning of the query.

The concept of [precedence of logical operators](http://www.cs.ucc.ie/~gavin/cs1001/Notes/chap40/ch40_16.html) exists and it defines exactly what is the order that should be implemented in any interpreter.

So, in my example, `foo and bar or xyz` means exactly the same as `(foo and bar) or xyz` and it can never be interpreted as `foo and (bar or xyz)` because  `and` has a higher precedence over `or`. 

This means that the combinators could be detached one from another without causing any “interpretation errors” (so to say).

**Comment by jakeboone02** [comment] 2021-06-22 16:15
Yeah, you're correct that in most domains the logical precedence is established.  However, it would be a major rewrite of this library to accommodate multiple combinators per group (not to mention many breaking changes).  So as you guessed, I'm going to close this ticket.  Thanks for the input, though!

**Comment by jakeboone02** [comment] 2021-11-01 17:51
I think I'm actually changing my mind about this one. I've started looking into adding an `inlineCombinators?: boolean` prop that would flip the `<QueryBuilder />` component from using `RuleGroupType` for the `query` and `onQueryChange` props to using a new type (tentatively named `RuleGroupTypeIC`) that would remove the `combinator` attribute and allow strings in the `rules` array. The intent would be to allow something like this:

```ts
const query: RuleGroupTypeIC = {
  rules: [
    { field: 'firstName', operator: '=', value: 'Name' },
    'and',
    { field: 'middleName', operator: '!=', value: 'Name' },
    'or',
    { field: 'lastName', operator: '=', value: 'Name' },
  ]
}
```

The `RuleGroup` component would render an independent `combinatorSelector` between each pair of rules.

I've got the functionality mostly working (along with modifications to `formatQuery` and `parseSQL`), but the TypeScript types are giving me headaches since I'm trying to maintain backwards compatibility and not export a completely separate base component. Once I get some good feedback on [this r/typescript post](https://www.reddit.com/r/typescript/comments/qjyqxq/switching_between_two_different_prop_types_in_one/), I'll fix up the types and create a PR that we can look at before merging.

**Closed as completed** 2021-11-03 06:37 UTC

**Comment by jakeboone02** [comment] 2021-11-03 06:54
Hey @alexandernst, I just released [v4.0.0-beta.3](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.0.0-beta.3) with the aforementioned `inlineCombinators` feature. Want to give it a whirl? I'm particularly interested in how the new TypeScript types fare, so it would be good if you're using TS. But any constructive feedback is welcome.

Edit: try [v4.0.0-beta.4](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.0.0-beta.4), actually. beta.3 was based on an outdated build.

**Comment by alexandernst** [comment] 2021-11-04 17:00
@jakeboone02 Absolutely! I'll upgrade to the latest beta and test the new feature :)
We're using JS, so I won't be able to test the TS types.

**Comment by jakeboone02** [comment] 2021-11-04 18:35
> We're using JS, so I won't be able to test the TS types.

No problem. It needs to work with JS, too! :)

**Comment by alexandernst** [comment] 2021-11-12 13:29
Hi @jakeboone02 ! Sorry for taking so long. It has been a really busy week. Fortunately, I'll have a lot of time during the weekend so I'll be able to test this.

**Comment by jakeboone02** [comment] 2021-11-12 13:36
Thanks, @alexandernst. Please note that I've just released v4.0.0-beta.5 which renames the prop to `independentCombinators`. (It also adds drag-and-drop support with the `enableDragAndDrop` prop, so give that a whirl if you want, too!)

**Comment by jakeboone02** [comment] 2021-11-12 13:38
[Release notes for latest beta](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.0.0-beta.5)

**Comment by alexandernst** [comment] 2021-11-15 12:20
@jakeboone02 I have been refactoring my code in order to adapt it to the new version; but I've hit a wall.

My use-case involves overriding the entire Rule component, but I can't find a way to do it with the code from the new beta. The Rule component uses some variables exports from the `defaults` and the `utils` (eg. https://github.com/react-querybuilder/react-querybuilder/blob/master/src/Rule.tsx#L5 ) files, but these variables are not exported in the distributable bundle, which means that

```
import { defaults, utils } from "react-querybuilder";

const { dndTypes, standardClassnames } = defaults;
const { c, getParentPath, getValidationClassNames, isAncestor, pathsAreEqual } = utils;
```

won't work.

**Comment by jakeboone02** [comment] 2021-11-15 15:43
Hmm.  I hadn't considered that.  I could expose `defaults`/`utils` in the main export.

Can you tell me what your requirement is that you need to replace the entire Rule component? Maybe we could accommodate your needs with the default component somehow.

**Comment by alexandernst** [comment] 2021-11-15 15:56
Sure thing! Actually my requirement is very simple (but still, it requires the entire component to be cloned). I just want to wrap all the controls in Row and Col bootstrap components, like so:

```
  return (
    <Row
      className={`rule ${classNames.rule} mt-2 ml-3 ${outerClassName}`}
      ref={dndRef}
      data-testid="rule"
      data-dragmonitorid={dragMonitorId}
      data-dropmonitorid={dropMonitorId}
      data-rule-id={id}
      data-level={level}
      data-path={JSON.stringify(path)}
    >
      <Col sm={4}>
        <controls.dragHandle
          ref={dragRef}
          level={level}
          title={translations.dragHandle.title}
          label={translations.dragHandle.label}
          className={c(standardClassnames.dragHandle, classNames.dragHandle)}
          context={context}
          validation={validationResult}
        />

        <controls.fieldSelector
          options={fields}
          title={translations.fields.title}
          value={field}
          operator={operator}
          className={c(standardClassnames.fields, classNames.fields)}
          handleOnChange={generateOnChangeHandler("field")}
          level={level}
          context={context}
          validation={validationResult}
        />
      </Col>

      {(autoSelectField || fieldData.name !== "~") ? (
        <>
          <Col sm={3}>
            <controls.operatorSelector
              field={field}
              fieldData={fieldData}
              title={translations.operators.title}
              options={operators}
              value={operator}
              className={c(standardClassnames.operators, classNames.operators)}
              handleOnChange={generateOnChangeHandler("operator")}
              level={level}
              context={context}
              validation={validationResult}
            />
          </Col>

          <Col sm={4}>
            <controls.valueEditor
              field={field}
              fieldData={fieldData}
              title={translations.value.title}
              operator={operator}
              value={value}
              type={valueEditorType}
              inputType={inputType}
              values={values}
              className={c(standardClassnames.value, classNames.value)}
              handleOnChange={generateOnChangeHandler("value")}
              level={level}
              context={context}
              validation={validationResult}
            />
          </Col>
        </>
      ) : (
        <Col sm={7}></Col>
      )}

      <Col sm={1} className="d-flex align-items-center">
        {showCloneButtons && (
          <controls.cloneRuleAction
            label={translations.cloneRule.label}
            title={translations.cloneRule.title}
            className={c(standardClassnames.cloneRule, classNames.cloneRule)}
            handleOnClick={cloneRule}
            level={level}
            context={context}
            validation={validationResult}
          />
        )}
        <controls.removeRuleAction
          label={translations.removeRule.label}
          title={translations.removeRule.title}
          className={c(standardClassnames.removeRule, classNames.removeRule)}
          handleOnClick={removeRule}
          level={level}
          context={context}
          validation={validationResult}
        />
      </Col>
    </Row>
  );
```

**Comment by jakeboone02** [comment] 2021-11-15 16:50
I think if you're just using bootstrap for alignment then you could do the same with [CSS Grid](https://css-tricks.com/snippets/css/complete-guide-grid/) without replicating the entire component.

**Comment by alexandernst** [comment] 2021-11-15 16:54
There is a little bit of logic involved as well. I'll probably swap the positions of some of the fields and maybe show/hide them completely base on certain logic. Hacking the component only with any sort of CSS might work, but it certainly won't be a clean solution, which is why I'd suggest to just export all the functions / variables required to inherit all / any of the components.

**Comment by jakeboone02** [comment] 2021-11-15 21:48
I would argue that a CSS solution would be _cleaner_ than replacing the `Rule` component. You can reorder elements with flexbox and align them with CSS Grid, placing extra classes on elements as necessary through the `controlClassnames` prop or with custom components besides `Rule`.

That said, it's probably OK to expose the defaults and utils anyway, so we'll try to do that in 4.0.

**Comment by alexandernst** [comment] 2021-11-15 21:58
Waiting for the next beta so I can test this and give you more feedback :)

**Comment by alexandernst** [comment] 2021-11-22 09:59
Hi @jakeboone02 ! Did you have the chance to apply the patch you mentioned earlier? I'm eager to keep testing the beta

**Comment by jakeboone02** [comment] 2021-11-22 15:11
Sorry it's taking so long! I meant to have another beta out sooner but life has gotten in the way lately. Anyway, I'm also swapping out the webpack build system for Parcel, reorganizing the TypeScript types, preparing a new documentation site, and converting the whole thing to a monorepo. That said, it shouldn't be too much longer. Thanks for your patience!

**Comment by jakeboone02** [comment] 2021-11-27 19:46
@alexandernst I just released [v4.0.0-beta.6](https://github.com/react-querybuilder/react-querybuilder/releases/tag/v4.0.0-beta.6) which exports all the defaults and utils as we discussed.

**Comment by alexandernst** [comment] 2021-11-27 19:47
Let me give it a try!

**Comment by alexandernst** [comment] 2021-11-29 15:41
@jakeboone02 I have some more feedback!

* The `InlineCombinator` is not exported, which forces me to copy the code of that element in order to override the `RuleGroup` component
* The drag&drop is not working properly when used in combination with Bootstrap's Rows and Cols. Example `RuleGroup` component that will fail: https://pastebin.com/JS6Z8GFE

Overall, the migration wasn't too complicated, I had to put ~half a day of work into it.

**Comment by alexandernst** [comment] 2021-11-29 15:58
Oh, I forgot to mention another thing I just noticed. There seems to be going on some type of casting with the values. This might actually be something that was already present in the 3.x branch, but I just noticed it now.

![aaa](https://user-images.githubusercontent.com/89727/143900664-acf30df3-af4c-4641-b317-9494c5ba2f28.png)

**Comment by jakeboone02** [comment] 2021-11-29 16:08
Thanks for taking a look!  I'll get `InlineCombinator` exported in the final 4.0 release.

I can't look at your pastebin example right now (work has blocked pastebin.com), but I can take a look after work. Or you could put an example up somewhere else, this [CodeSandbox template](https://codesandbox.io/s/react-querybuilder-ci-oq8ts) is what we use for CI, so it's a good starting point.

On the number thing, `react-querybuilder` is just using the `value` reported by the `<input>` element by default, which is always a string in the case of standard HTML `<input>`s (even for `<input type="number">`). So you'd need to use either a custom `ValueEditor` or a custom `valueProcessor` in `formatQuery` to get an actual `number`-type value in your export string.

**Comment by alexandernst** [comment] 2021-11-29 17:00
I created a demo for the D&D bug: https://codesandbox.io/s/react-querybuilder-ci-forked-je5f3

About the casting, gotcha!

**Comment by jakeboone02** [comment] 2021-11-29 21:19
In your codesandbox example, you weren't assigning the custom `RuleGroup` component to the `controlElements` prop in the `<QueryBuilder />` call, so it was just using the default component. Also, you were generating a query object of type `RuleGroupType` when it should have been `RuleGroupTypeIC` since the `independentCombinators` prop was set to `true`, (i.e. the `parseSQL` call _also_ needed the `independentCombinators` option set to `true`).

I've fixed the errors and I think it's working here: https://codesandbox.io/s/react-querybuilder-react-bootstrap-rulegroup-3o869?file=/src/App.tsx

**Comment by alexandernst** [comment] 2021-11-30 10:43
HI @jakeboone02 ! I'm sorry for the demo, something went wrong and my changes weren't applied properly. Thank you for looking at the code anyways.

That said, there seems to be yet another bug. Using your own example, try to drag the "Age" row on top of the "Last name" row. I end up seeing this:

![react-querybuilder_react-bootstrap_RuleGroup_-_CodeSandbox](https://user-images.githubusercontent.com/89727/144032815-d8f95feb-a387-4ef8-9a06-55dcda5253fb.png)

**Comment by jakeboone02** [comment] 2021-11-30 15:13
@alexandernst - confirmed. It seems the move works if you drop the Age rule directly over the First Name rule, but not if you drop it on the combinator selector below it. Should be the same effect for both.

**Comment by jakeboone02** [comment] 2021-12-13 01:05
@alexandernst I think I fixed the bug with drag-and-drop when using `independentCombinators` (see #246). Would you mind trying out [v4.0.0-beta.7](/react-querybuilder/react-querybuilder/releases/tag/v4.0.0-beta.7) and confirming before I release 4.0 final?

**Comment by alexandernst** [comment] 2022-01-09 23:44
Hey @jakeboone02 ! Sorry for the long delay in the response; took some vacations (holidays and so). I tested the 4.0 and everything looks good! The dnd bug is completely gone. I have just one small complaint about breaking compatibility on the format level, but I'll open a new bug for that.

Kudos for the great work!
